# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# CreateServiceLine.py
# Created on: 2015-12-14 21:25:43.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: CreateServiceLine <xyXYServiceLine> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")

# Script arguments
xyXYServiceLine = arcpy.GetParameterAsText(0)
if xyXYServiceLine == '#' or not xyXYServiceLine:
    xyXYServiceLine = "I:\\DataNScripts\\Enterprise\\awasvikas\\AVASH VIKASH\\xyXYServiceLine" # provide a default value if unspecified

# Local variables:
Building_FeatureToPoint__2_ = "Building_FeatureToPoint"
Support_Structure__2_ = "Support Structure"
xyXYServiceLine__2_ = xyXYServiceLine
xyXYServiceLine__6_ = xyXYServiceLine__2_
xyXYServiceLine__3_ = xyXYServiceLine__6_
xyXYServiceLine__4_ = xyXYServiceLine__3_
AVASH_VIKASH = "I:\\DataNScripts\\Enterprise\\awasvikas\\AVASH VIKASH"
LT_Overhead_Line__2_ = "LT Overhead Line"
Building_FeatureToPoint__3_ = "Building_FeatureToPoint"
Support_Structure = "Support Structure"
Building_FeatureToPoint__4_ = "Support Structure"
SupportStructure_XYToLine = "I:\\DataNScripts\\Enterprise\\awasvikas\\fwdawasvikashpgdb\\PuVVNL_VARANASI_DIV6_21AUG15.mdb\\ElectricDataset\\SupportStructure_XYToLine"
Building_FeatureToPoint = "Building_FeatureToPoint"

# Process: Create Table
arcpy.CreateTable_management(AVASH_VIKASH, "xyXYServiceLine", "", "")

# Process: Add Field
arcpy.AddField_management(xyXYServiceLine, "xStart", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (2)
arcpy.AddField_management(xyXYServiceLine__2_, "yStart", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (3)
arcpy.AddField_management(xyXYServiceLine__6_, "xFinish", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (4)
arcpy.AddField_management(xyXYServiceLine__3_, "yFinish", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(Building_FeatureToPoint__2_, "NEW_SELECTION", "\"BUILDINGID\" = '07607371030'")

# Process: Add XY Coordinates
arcpy.AddXY_management(Building_FeatureToPoint__3_)

# Process: Get Field Value
arcpy.GetFieldValue_mb(Building_FeatureToPoint, "POINT_X", "", "0")

# Process: Select Layer By Attribute (2)
arcpy.SelectLayerByAttribute_management(Support_Structure__2_, "NEW_SELECTION", "[GISID] = '40004084137'")

# Process: Add XY Coordinates (2)
arcpy.AddXY_management(Support_Structure)

# Process: XY To Line
arcpy.XYToLine_management(Building_FeatureToPoint__4_, SupportStructure_XYToLine, "", "", "POINT_X", "POINT_Y", "GEODESIC", "", "PROJCS['WGS_1984_UTM_Zone_44N',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',81.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]];-5120900 -9998100 10000;-100000 10000;0 1;0.001;0.001;0.001;IsHighPrecision")

# Process: Append
arcpy.Append_management("I:\\DataNScripts\\Enterprise\\awasvikas\\fwdawasvikashpgdb\\PuVVNL_VARANASI_DIV6_21AUG15.mdb\\ElectricDataset\\SupportStructure_XYToLine", LT_Overhead_Line__2_, "TEST", "", "")

