# ---------------------------------------------------------------------------
# createFireFeature.py
# Created on: 2011-06-06 13:43:15.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Feature_Class_Location = "D:\\"
fire01_11_shp = "D:\\fire01_11.shp"

# Process: Create Feature Class
arcpy.CreateFeatureclass_management(Feature_Class_Location, "fireFeature.shp", "POINT", "D:\\fire01_11.shp", "DISABLED", "DISABLED", "PROJCS['WGS_1984_UTM_Zone_45N',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',87.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]];-5120900 -9998100 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision", "", "0", "0", "0")

