# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# CreatePersonalGeodatabaseFromModelbuilder.py
# Created on: 2016-07-16 17:53:25.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
gis = "C:\\Users\\ajay\\Documents\\gis"

# Process: Create Personal GDB
arcpy.CreatePersonalGDB_management(gis, "CreatedPersonaGeodatabaseFromModelBuiler", "CURRENT")

