# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# IteratorModelBuilderExperiment1.py
# Created on: 2016-07-16 12:18:50.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


# Local variables:
PuVVNL_VARANASI_DIV6_2DEC15-Copy_mdb = "C:\\Users\\ajay\\Documents\\gis\\VARANASI_DIV6\\PuVVNL_VARANASI_DIV6_2DEC15-Copy.mdb"
BusBar = "C:\\Users\\ajay\\Documents\\gis\\VARANASI_DIV6\\PuVVNL_VARANASI_DIV6_2DEC15-Copy.mdb\\ElectricDataset\\BusBar"

# Process: Iterate Feature Classes
arcpy.IterateFeatureClasses_mb(PuVVNL_VARANASI_DIV6_2DEC15-Copy_mdb, "", "", "NOT_RECURSIVE")

# Process: Get Field Value
arcpy.GetFieldValue_mb(BusBar, "CREATIONUSER", "String", "")

