# ---------------------------------------------------------------------------
# makeFireFeatureLayer.py
# Created on: 2011-06-06 11:19:35.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
fire01_11 = "fire01_11"
fire01_11_shp = "D:\\fire01_11.shp"
fire01_11_Layer = "D:\\fire01_11_Layer"

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(fire01_11_shp, fire01_11_Layer, "", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;LATITUDE LATITUDE VISIBLE NONE;LONGITUDE LONGITUDE VISIBLE NONE;BRIGHTNESS BRIGHTNESS VISIBLE NONE;SCAN SCAN VISIBLE NONE;TRACK TRACK VISIBLE NONE;ACQ_DATE ACQ_DATE VISIBLE NONE;ACQ_TIME ACQ_TIME VISIBLE NONE;SATELLITE SATELLITE VISIBLE NONE;CONFIDENCE CONFIDENCE VISIBLE NONE;VERSION VERSION VISIBLE NONE;BRIGHT_T31 BRIGHT_T31 VISIBLE NONE;FRP FRP VISIBLE NONE")

