# ---------------------------------------------------------------------------
# ModelBuilderExtensiveExperiment.py
# Created on: 2015-08-23 20:13:17.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


# Local variables:
Distribution_Transformer__2_ = "Distribution Transformer"
customerinfo_xlsx = "I:\\DataNScripts\\Enterprise\\awasvikas\\customerinfo.xlsx"
Service_Point = "Service Point"
Table = "I:\\DataNScripts\\Enterprise\\awasvikas\\customerinfo.xlsx\\Table"
Table_Layer = "Table_Layer"
Table_CopyFeatures = "C:\\Users\\ajay\\Documents\\ArcGIS\\Default1.gdb\\Table_CopyFeatures"

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(Distribution_Transformer__2_, "NEW_SELECTION", "[GISID] = '400090513' ")

# Process: Iterate Tables
arcpy.IterateTables_mb(customerinfo_xlsx, "", "DBASE", "NOT_RECURSIVE")

# Process: Make XY Event Layer
arcpy.MakeXYEventLayer_management(Table, "", "", Table_Layer, "", "")

# Process: Copy Features
arcpy.CopyFeatures_management(Table_Layer, Table_CopyFeatures, "", "0", "0", "0")

# Process: Append
arcpy.Append_management("C:\\Users\\ajay\\Documents\\ArcGIS\\Default1.gdb\\Table_CopyFeatures", Service_Point, "TEST", "", "")

