# ---------------------------------------------------------------------------
# selByAttribute.py
# Created on: 2011-07-07 21:13:00.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
forestBlocst__2_ = "I:\\GISAUTMATION\\forestBlocst.shp"
forestBlocst = "forestBlocst"
BTR_W__lyr = "C:\\Project\\BTR(W)1.lyr"

# Process: Select Layer By Attribute
forestBlocst=arcpy.SelectLayerByAttribute_management(forestBlocst__2_, "NEW_SELECTION", "\"DIVISION\" =  'BTR WEST'")

# Process: Save To Layer File
arcpy.SaveToLayerFile_management(forestBlocst, BTR_W__lyr, "")

