# ---------------------------------------------------------------------------
# selectByAttribute2.py
# Created on: 2011-07-07 21:31:08.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
forestBlocst__2_ = "I:\\GISAUTMATION\\forestBlocst.shp"
Output_Layer = "forestBlocst_Layer"
forestBlocst = "forestBlocst_Layer"
BTR_W_3_shp = "C:\\Project\\BTRW3.shp"

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(forestBlocst__2_, Output_Layer, "", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;Join_Count Join_Count VISIBLE NONE;FID_1 FID_1 VISIBLE NONE;CIRCLE CIRCLE VISIBLE NONE;DISTRICT DISTRICT VISIBLE NONE;DIVISION DIVISION VISIBLE NONE;RANGE RANGE VISIBLE NONE;BEAT BEAT VISIBLE NONE;MOUZA MOUZA VISIBLE NONE;JL_NO JL_NO VISIBLE NONE;PS PS VISIBLE NONE;F_BLOCK F_BLOCK VISIBLE NONE;F_COMP F_COMP VISIBLE NONE;IFS_Code IFS_Code VISIBLE NONE;NIC_Mail NIC_Mail VISIBLE NONE;Other_Mail Other_Mail VISIBLE NONE;Name Name VISIBLE NONE;Name1 Name1 VISIBLE NONE;Mobile Mobile VISIBLE NONE;Div1 Div1 VISIBLE NONE;Div Div VISIBLE NONE;IFS_Code_1 IFS_Code_1 VISIBLE NONE;NIC_Mail_1 NIC_Mail_1 VISIBLE NONE;Other_Ma_1 Other_Ma_1 VISIBLE NONE;Other_Ma_2 Other_Ma_2 VISIBLE NONE;Name_1 Name_1 VISIBLE NONE;Name1_1 Name1_1 VISIBLE NONE;Mobile_1 Mobile_1 VISIBLE NONE;Circle1 Circle1 VISIBLE NONE;Circle_1 Circle_1 VISIBLE NONE;LATITUDE LATITUDE VISIBLE NONE;LONGITUDE LONGITUDE VISIBLE NONE;BRIGHTNESS BRIGHTNESS VISIBLE NONE;SCAN SCAN VISIBLE NONE;TRACK TRACK VISIBLE NONE;ACQ_DATE ACQ_DATE VISIBLE NONE;ACQ_TIME ACQ_TIME VISIBLE NONE;SATELLITE SATELLITE VISIBLE NONE;CONFIDENCE CONFIDENCE VISIBLE NONE;VERSION VERSION VISIBLE NONE;BRIGHT_T31 BRIGHT_T31 VISIBLE NONE;FRP FRP VISIBLE NONE")

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(Output_Layer, "NEW_SELECTION", "\"DIVISION\" =  'BTR WEST'")

# Process: Copy Features
arcpy.CopyFeatures_management(forestBlocst, BTR_W_3_shp, "", "0", "0", "0")

