# ---------------------------------------------------------------------------
# select.py
# Created on: 2011-07-08 23:38:12.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
wbattributedCleaned_Layer = "wbattributedCleaned_Layer"
wbattributedCleaned_Layer1 = "wbattributedCleaned_Layer1"

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(wbattributedCleaned_Layer, wbattributedCleaned_Layer1, "", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;FID_1 FID_1 VISIBLE NONE;CIRCLE CIRCLE VISIBLE NONE;DISTRICT DISTRICT VISIBLE NONE;DIVISION DIVISION VISIBLE NONE;RANGE RANGE VISIBLE NONE;BEAT BEAT VISIBLE NONE;MOUZA MOUZA VISIBLE NONE;JL_NO JL_NO VISIBLE NONE;PS PS VISIBLE NONE;F_BLOCK F_BLOCK VISIBLE NONE;F_COMP F_COMP VISIBLE NONE")

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(wbattributedCleaned_Layer1, "NEW_SELECTION", "\"RANGE\" = 'AMBARI'")

